### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by alydersen** [espen/visma-eaccounting#1]
Hi and thank you for doing all this work and releasing it to the public.

I'm having issues using the sandbox environment. The authentication runs nicely, but any other call from there seems to go through the production URLs.

These will both raise Syntax Errors:
visma_eaccounting = VismaEaccounting::Request.new(token: current_user.visma_eaccounting_token, :sandbox)
or
visma_eaccounting = VismaEaccounting::Request.new(token: current_user.visma_eaccounting_token, environment: :sandbox)

And it doesn't seem to want it in the initialiser either.

Any hints on what I'm doing wrong?

BR,
Andreas

**Comment by espen** [comment]
Try `api_environment`. Sorry should document it better.

**Comment by espen** [comment]
Fixed by https://github.com/espen/visma_eaccounting/commit/f6c25bcba05c1e50f76dad765d9fc053064c2221
