### ISSUE TITLE
Customer Create returns error 400

### ISSUE THREAD

**Issue by alydersen** [espen/visma-eaccounting#2]
Hi,

When trying to create a customer, even with the exact example from the Readme, I get:
```
Faraday::ClientError: 
the server responded with status 400
```
Command is e.g. `visma_eaccounting.customers.create(body: {"Name": "MakePlans AS"})`

Any hints as to why this happens? I've also tried to supply more arguments, such as "IsPrivatePerson" and "CustomerNumber".

Andreas

**Comment by espen** [comment]
Doesn't it return a VismaEaccounting::APIError?

Anyways, the example isn't working. You need to specify InvoiceCity, InvoicePostalCode, TermsOfPaymentId and IsPrivatePerson. This is required by the Visma API. Will update the example later.

here is the response I get with that command:

`VismaEaccounting::APIError (the server responded with status 400 @title=nil, @detail=nil, @body={"ErrorCode"=>2000, "DeveloperErrorMessage"=>"ValidateModelAttributeException - Required property 'TermsOfPaymentId' not found in JSON. Path '', line 1, position 27. The InvoiceCity field is required. The InvoicePostalCode field is required. The IsPrivatePerson field is required. ", "ErrorId"=>"818f9099-6ad7-4a46-9625-bcde0f0e5091"}, @raw_body="{\"ErrorCode\":2000,\"DeveloperErrorMessage\":\"ValidateModelAttributeException - Required property 'TermsOfPaymentId' not found in JSON. Path '', line 1, position 27. The InvoiceCity field is required. The InvoicePostalCode field is required. The IsPrivatePerson field is required. \",\"ErrorId\":\"818f9099-6ad7-4a46-9625-bcde0f0e5091\"}", @status_code=400)`

**Comment by alydersen** [comment]
I'm only getting the faraday error and not the VismaEaccounting one. Using:
```
ruby '2.5.1'
gem 'rails', '~> 5.1.4'
```
Even with the new params, I'm still getting the error:
```
customer = {:Name=>"Testkunde AS", :IsPrivatePerson=>false, :InvoiceCity=>"MOSS", :InvoicePostalCode=>"1500", :InvoiceCountryCode=>"NO", :CurrencyCode=>"NOK", :TermsOfPaymentId=>"8f9a8f7b-5ea9-44c6-9725-9b8a1addb036"}
k = visma_eaccounting.customers.create(body: customer)
```

Is there a way to get all the payment terms?

**Comment by espen** [comment]
That's odd.

You can get a list of all payments terms using: `visma_eaccounting.termsofpayments.retrieve.body['Data']`
